# Generated by Django 3.1.2 on 2022-09-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('idautor', models.IntegerField(primary_key=True, serialize=False)),
                ('autor', models.CharField(max_length=30)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Bodegas',
            fields=[
                ('idbodega', models.IntegerField(primary_key=True, serialize=False)),
                ('espacio_de_bodega', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Editoriales',
            fields=[
                ('ideditorial', models.IntegerField(primary_key=True, serialize=False)),
                ('editorial', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
            ],
        ),
    ]
