# Generated by Django 3.1.2 on 2022-09-15 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.autores')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.bodegas')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.editoriales')),
            ],
        ),
    ]
